import { PipelineConfig, ScheduledPipeline } from './types';
import { generateSQL } from './code-generator';

export function generateTaskSQL(
  scheduledPipeline: ScheduledPipeline,
  pipeline: PipelineConfig,
  allScheduledPipelines: ScheduledPipeline[]
): string {
  const statements: string[] = [];
  const taskName = sanitizeIdentifier(`TASK_${scheduledPipeline.pipelineName}`);
  
  const pipelineSQL = generateSQL(
    pipeline.nodes.map(n => ({
      id: n.id,
      type: 'etlNode',
      position: n.position,
      data: n.data,
    })),
    pipeline.edges
  );

  const procedureName = sanitizeIdentifier(`SP_${scheduledPipeline.pipelineName}`);
  statements.push(`-- Stored Procedure for ${scheduledPipeline.pipelineName}`);
  statements.push(`CREATE OR REPLACE PROCEDURE ${procedureName}()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
${pipelineSQL.split('\n').map(line => '  ' + line).join('\n')}
  RETURN 'SUCCESS';
END;
$$;`);

  statements.push('');
  statements.push(`-- Task for ${scheduledPipeline.pipelineName}`);
  
  let taskDef = `CREATE OR REPLACE TASK ${taskName}`;
  taskDef += `\n  WAREHOUSE = ${scheduledPipeline.taskConfig.warehouse}`;
  
  if (scheduledPipeline.dependencies.length > 0) {
    const parentTask = allScheduledPipelines.find(sp => sp.id === scheduledPipeline.dependencies[0]);
    if (parentTask) {
      const parentTaskName = sanitizeIdentifier(`TASK_${parentTask.pipelineName}`);
      taskDef += `\n  AFTER ${parentTaskName}`;
    }
  } else {
    if (scheduledPipeline.schedule.type === 'cron' && scheduledPipeline.schedule.cron) {
      taskDef += `\n  SCHEDULE = 'USING CRON ${scheduledPipeline.schedule.cron} ${scheduledPipeline.schedule.timezone || 'UTC'}'`;
    } else if (scheduledPipeline.schedule.type === 'interval' && scheduledPipeline.schedule.intervalMinutes) {
      taskDef += `\n  SCHEDULE = '${scheduledPipeline.schedule.intervalMinutes} MINUTE'`;
    }
  }
  
  if (scheduledPipeline.taskConfig.errorIntegration) {
    taskDef += `\n  ERROR_INTEGRATION = ${scheduledPipeline.taskConfig.errorIntegration}`;
  }
  
  if (scheduledPipeline.taskConfig.allowOverlappingExecution !== undefined) {
    taskDef += `\n  ALLOW_OVERLAPPING_EXECUTION = ${scheduledPipeline.taskConfig.allowOverlappingExecution ? 'TRUE' : 'FALSE'}`;
  }
  
  if (scheduledPipeline.taskConfig.suspendTaskAfterFailures) {
    taskDef += `\n  SUSPEND_TASK_AFTER_NUM_FAILURES = ${scheduledPipeline.taskConfig.suspendTaskAfterFailures}`;
  }
  
  if (scheduledPipeline.taskConfig.userTaskTimeoutMs) {
    taskDef += `\n  USER_TASK_TIMEOUT_MS = ${scheduledPipeline.taskConfig.userTaskTimeoutMs}`;
  }
  
  taskDef += `\nAS\n  CALL ${procedureName}();`;
  
  statements.push(taskDef);
  
  statements.push('');
  if (scheduledPipeline.enabled) {
    statements.push(`ALTER TASK ${taskName} RESUME;`);
  } else {
    statements.push(`-- Task created in suspended state. Run the following to enable:`);
    statements.push(`-- ALTER TASK ${taskName} RESUME;`);
  }
  
  return statements.join('\n');
}

export function generateAllTasksSQL(
  scheduledPipelines: ScheduledPipeline[],
  pipelines: PipelineConfig[]
): string {
  const sortedPipelines = topologicalSort(scheduledPipelines);
  const statements: string[] = [
    '-- ============================================',
    '-- SNOWFLAKE TASK ORCHESTRATION',
    '-- Generated by Data Pipeline Builder',
    `-- Generated at: ${new Date().toISOString()}`,
    '-- ============================================',
    '',
  ];
  
  for (const sp of sortedPipelines) {
    const pipeline = pipelines.find(p => p.id === sp.pipelineId);
    if (pipeline) {
      statements.push(generateTaskSQL(sp, pipeline, scheduledPipelines));
      statements.push('');
    }
  }
  
  const rootTasks = sortedPipelines.filter(sp => sp.dependencies.length === 0 && sp.enabled);
  if (rootTasks.length > 0) {
    statements.push('-- ============================================');
    statements.push('-- RESUME ROOT TASKS (run after all tasks are created)');
    statements.push('-- ============================================');
    for (const rt of rootTasks) {
      const taskName = sanitizeIdentifier(`TASK_${rt.pipelineName}`);
      statements.push(`ALTER TASK ${taskName} RESUME;`);
    }
  }
  
  return statements.join('\n');
}

function topologicalSort(pipelines: ScheduledPipeline[]): ScheduledPipeline[] {
  const visited = new Set<string>();
  const result: ScheduledPipeline[] = [];
  const pipelineMap = new Map(pipelines.map(p => [p.id, p]));
  
  function visit(id: string) {
    if (visited.has(id)) return;
    visited.add(id);
    
    const pipeline = pipelineMap.get(id);
    if (pipeline) {
      for (const depId of pipeline.dependencies) {
        visit(depId);
      }
      result.push(pipeline);
    }
  }
  
  for (const p of pipelines) {
    visit(p.id);
  }
  
  return result;
}

function sanitizeIdentifier(name: string): string {
  return name.toUpperCase().replace(/[^A-Z0-9_]/g, '_');
}

export const CRON_PRESETS = [
  { label: 'Every minute', cron: '* * * * *' },
  { label: 'Every 5 minutes', cron: '*/5 * * * *' },
  { label: 'Every 15 minutes', cron: '*/15 * * * *' },
  { label: 'Every 30 minutes', cron: '*/30 * * * *' },
  { label: 'Every hour', cron: '0 * * * *' },
  { label: 'Every 6 hours', cron: '0 */6 * * *' },
  { label: 'Daily at midnight', cron: '0 0 * * *' },
  { label: 'Daily at 6 AM', cron: '0 6 * * *' },
  { label: 'Daily at noon', cron: '0 12 * * *' },
  { label: 'Weekly (Sunday midnight)', cron: '0 0 * * 0' },
  { label: 'Monthly (1st at midnight)', cron: '0 0 1 * *' },
];

export const TIMEZONES = [
  'UTC',
  'America/New_York',
  'America/Chicago',
  'America/Denver',
  'America/Los_Angeles',
  'Europe/London',
  'Europe/Paris',
  'Asia/Tokyo',
  'Asia/Singapore',
  'Australia/Sydney',
];
